# Generated by Django 6.0.1 on 2026-01-18 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('pocket_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_lesson', models.IntegerField(default=0)),
                ('user_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
