# Generated by Django 5.2.10 on 2026-01-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesmodel',
            name='description',
        ),
    ]
